version: 3.0.4.1
services:
  paperlessai:
    image: clusterzx/paperless-ai:3.0.4
    container_name: paperless-ai
    network_mode: bridge
    restart: on-failure
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    environment:
      - PUID=1000
      - PGID=1000
      - PAPERLESS_AI_PORT=${PAPERLESS_AI_PORT:-3000}
      - RAG_SERVICE_URL=http://localhost:8000
      - RAG_SERVICE_ENABLED=true
    ports:
      - 3000:${PAPERLESS_AI_PORT:-3000}
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
